---
- name: Test privilege escalation
  hosts: all
  remote_user: ansibleclient
  gather_facts: false

  tasks:

    - name: Check current user
      ansible.builtin.command:
        cmd: id
      register: before
      changed_when: false

    - name: Display current user
      ansible.builtin.debug:
        var: before.stdout

    - name: Run id through sudo
      ansible.builtin.command:
        cmd: sudo -n id
      register: sudo_test
      changed_when: false

    - name: Display sudo result
      ansible.builtin.debug:
        var: sudo_test.stdout

    - name: Run vgs through sudo
      ansible.builtin.command:
        cmd: sudo -n vgs --noheadings --units g --nosuffix -o vg_free root-vg
      register: vgs_test
      changed_when: false

    - name: Display vgs result
      ansible.builtin.debug:
        var: vgs_test
