---
- name: webhook test
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002

  rules:
    - name: Receive webhook
      condition: event.payload.eventType == "AVAILABILITY"
      action:
        run_job_template:
          name: Uptimecheck
          organization: Default
